#!/usr/bin/env python3
"""Stock researcher arm — fundamental + quant factor screening for multibaggers.

Advisory only. Never publishes order intents. Outputs:
- intel/stock_research.jsonl (audit ledger)
- intel/stock_research_latest.json (dashboard/agent context)
- config/instruments.d/research_active.yaml (optional watchlist overlay)
- bus: research.stock.ranked, research.stock.alert

Run once:
  python research/stock_researcher.py --once

Continuous (supervisor):
  python research/stock_researcher.py
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "nervous"))

from bus import publish  # noqa: E402
from cortex.instrument_registry import InstrumentRegistry  # noqa: E402
from research.config import load_config  # noqa: E402
from research.news_context import build_news_context  # noqa: E402
from research.research_packet import derive_packet, write_memo  # noqa: E402
from research.stock_factors import build_research_row, rank_research_rows  # noqa: E402
from research.stock_fundamentals import fetch_universe, yfinance_available  # noqa: E402

DEFAULT_INTERVAL = int(os.getenv("STOCK_RESEARCH_INTERVAL", "86400"))


def resolve_universe(registry: InstrumentRegistry, cfg: Dict[str, Any]) -> List[str]:
    uni = cfg.get("universe") or {}
    asset_class = str(uni.get("asset_class") or "stock_cfd")
    region = uni.get("region")
    max_symbols = int(uni.get("max_symbols") or 50)
    include_disabled = bool(uni.get("include_disabled", True))

    if include_disabled:
        symbols = registry.symbols_matching(asset_class=asset_class, region=region) if region else [
            sym for sym, meta in registry.symbols.items() if str(meta.get("asset_class") or "") == asset_class
        ]
    else:
        symbols = registry.enabled_symbols(asset_class=asset_class, region=region)

    symbols = sorted({str(s).upper() for s in symbols if s})
    return symbols[:max_symbols]


def symbol_meta(registry: InstrumentRegistry, symbols: List[str]) -> Dict[str, Dict[str, Any]]:
    out: Dict[str, Dict[str, Any]] = {}
    for sym in symbols:
        meta = registry.get(sym) or {}
        out[sym] = {
            "region": meta.get("region") or "US",
            "exchange": meta.get("exchange") or "",
            "yfinance_ticker": meta.get("yfinance_ticker"),
            "enabled": meta.get("enabled"),
        }
    return out


def write_snapshot(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def append_ledger(path: Path, record: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, sort_keys=True) + "\n")


def write_research_overlay(path: Path, ranked: List[Dict[str, Any]], *, min_confidence: float) -> None:
    """Write advisory overlay for high-confidence names (does not auto-enable trading)."""
    picks = [r for r in ranked if float(r.get("confidence") or 0) >= min_confidence and r.get("tier") != "watch"]
    if not picks:
        return
    lines = [
        "# Auto-generated by stock_researcher.py — advisory watchlist overlay",
        "# Does NOT enable symbols; set enabled: true manually after broker verification.",
        f"# generated_ts: {time.time()}",
        "",
        "symbols:",
    ]
    for row in picks[:15]:
        sym = row["symbol"]
        lines.extend(
            [
                f"  {sym}:",
                "    research_tier: " + str(row.get("tier")),
                "    research_confidence: " + str(row.get("confidence")),
                "    research_score: " + str(row.get("composite_score")),
                f"    thesis: \"{row.get('thesis', '')}\"",
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _propose_symbol_enables(ranked: List[Dict[str, Any]], cfg: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Advisory: surface high-conviction names as enable proposals.

    Never auto-enables trading; only publishes a proposal for human review.
    """
    proposals = [
        {
            "symbol": row.get("symbol"),
            "tier": row.get("tier"),
            "confidence": row.get("confidence"),
            "final_score": row.get("final_score"),
        }
        for row in ranked
        if row.get("tier") in {"multibagger_candidate", "high_conviction"}
    ]
    if proposals:
        publish(
            "research.stock.enable_proposal",
            {"ts": time.time(), "proposals": proposals, "advisory_only": True},
        )
    return proposals


def run_once(*, cfg: Optional[Dict[str, Any]] = None, persist: bool = True) -> Dict[str, Any]:
    cfg = cfg or load_config()
    registry = InstrumentRegistry(ROOT / "config" / "instruments.yaml")
    symbols = resolve_universe(registry, cfg)
    meta = symbol_meta(registry, symbols)

    fundamentals = fetch_universe(symbols, meta_by_symbol=meta)
    rows = [build_research_row(sym, fundamentals.get(sym) or {}, cfg=cfg) for sym in symbols]
    ranked = rank_research_rows(rows)

    # Pull recent per-symbol news context (catalysts + tone) from the headline
    # cache so packets and final_score reflect news, not just fundamentals.
    try:
        news_by_symbol = build_news_context(symbols)
    except Exception as exc:
        news_by_symbol = {}
        publish("cortex.fallback", {"layer": "stock_researcher", "error": f"news_context:{exc}", "action": "skip_news"})

    ranked = [
        derive_packet(row, news=news_by_symbol.get(str(row.get("symbol") or "").upper()))
        for row in ranked
    ]

    thresholds = cfg.get("thresholds") or {}
    publish_min = float(thresholds.get("publish_min_confidence", 0.68))
    top = [r for r in ranked if float(r.get("confidence") or 0) >= publish_min][:20]
    multibaggers = [r for r in ranked if r.get("tier") == "multibagger_candidate"]
    accumulate = [r for r in ranked if r.get("tier") in {"high_conviction", "accumulate"}]

    payload = {
        "ts": time.time(),
        "source": "stock_researcher",
        "advisory_only": True,
        "yfinance_available": yfinance_available(),
        "universe_size": len(symbols),
        "ranked_count": len(ranked),
        "ranked": ranked,
        "top_picks": top,
        "multibagger_candidates": multibaggers,
        "accumulate": accumulate,
        "methodology": {
            "factors": ["quality", "growth", "value", "momentum", "multibagger"],
            "weights": cfg.get("weights"),
            "thresholds": thresholds,
            "note": "Quant-style composite; not investment advice. Validate with walk-forward and risk limits.",
        },
    }

    if persist:
        out = cfg.get("output") or {}
        ledger = ROOT / str(out.get("ledger") or "intel/stock_research.jsonl")
        snapshot = ROOT / str(out.get("snapshot") or "intel/stock_research_latest.json")
        overlay = ROOT / str(out.get("overlay") or "config/instruments.d/research_active.yaml")

        append_ledger(ledger, payload)
        write_snapshot(snapshot, payload)
        write_research_overlay(overlay, ranked, min_confidence=publish_min)
        _propose_symbol_enables(ranked, cfg)

        memo_packets = sorted(ranked, key=lambda r: float(r.get("final_score") or 0.0), reverse=True)
        payload["research_memo"] = write_memo(memo_packets)

        pub = cfg.get("publish") or {}
        topic = str(pub.get("bus_topic_ranked") or "research.stock.ranked")
        publish(topic, payload)
        if multibaggers:
            alert_topic = str(pub.get("bus_topic_alert") or "research.stock.alert")
            publish(alert_topic, {"ts": time.time(), "candidates": multibaggers, "advisory_only": True})

    return payload


def run(interval: float = DEFAULT_INTERVAL) -> None:
    print(f"[stock_researcher] interval={interval}s yfinance={yfinance_available()}", flush=True)
    while True:
        try:
            result = run_once()
            top = result.get("top_picks") or []
            mb = result.get("multibagger_candidates") or []
            print(
                f"[stock_researcher] ranked={result.get('ranked_count')} top={len(top)} multibaggers={len(mb)}",
                flush=True,
            )
            for row in mb[:5]:
                print(
                    f"  MB {row.get('symbol')} conf={row.get('confidence')} score={row.get('composite_score')} {row.get('thesis')}",
                    flush=True,
                )
        except Exception as exc:
            publish("cortex.fallback", {"layer": "stock_researcher", "error": str(exc), "action": "crash"})
        time.sleep(interval)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Fundamental stock researcher / multibagger screener")
    parser.add_argument("--once", action="store_true", help="Run one research cycle and exit")
    parser.add_argument("--interval", type=float, default=DEFAULT_INTERVAL)
    parser.add_argument("--no-persist", action="store_true")
    args = parser.parse_args(argv)
    if args.once:
        payload = run_once(persist=not args.no_persist)
        print(json.dumps(payload, indent=2, default=str))
        return 0
    run(args.interval)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
