#!/usr/bin/env python3
"""
swarm/code_gen.py — Strategy Code Generator
--------------------------------------------
Generates MQL5 or Python strategy code from a hypothesis spec.
Produces a complete, runnable strategy module.
"""
import json, os, time
from pathlib import Path

TASK = json.loads(os.environ.get("SWARM_TASK", "{}"))
OUT = os.environ.get("SWARM_OUT", "/tmp/swarm_code_gen.json")

SPEC = TASK.get("spec", {})
NAME = SPEC.get("id", "unnamed_strategy")
TYPE = SPEC.get("type", "trend_following")

# ------------------ MQL5 Template System ------------------

def generate_mql5(spec):
    inds = spec.get("indicators", [])
    ind_decl = "\n".join([f"int    handle_{i.lower().replace(' ','_')};" for i in inds]) if inds else "// No indicators"
    
    entry = spec.get("entry_logic", "true")
    exit_logic = spec.get("exit_logic", "true")
    
    code = f'''//+------------------------------------------------------------------+
//|  Auto-generated strategy: {NAME}                    |
//|  Type: {TYPE}                                        |
//+------------------------------------------------------------------+
#property copyright "Trading OS"
#property link      "https://trading-os.local"
#property version   "1.00"
#property strict

input double InpRiskPercent = 1.0;   // Risk per trade %
input double InpSlAtrMult   = 1.5;   // SL = ATR * multiplier
input double InpTpRr        = 2.0;   // Take profit R:R
input int    InpMagic       = 1337;  // Magic number

{ind_decl}

double atr_cache = 0;
//+------------------------------------------------------------------+
int OnInit()
{{
   //--- Initialize indicators
   for(int i=0; i<ArraySize(inds); i++) {{ /* init handles */ }}
   return(INIT_SUCCEEDED);
}}
//+------------------------------------------------------------------+
void OnTick()
{{
   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return;
   
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   
   // Position check
   bool has_pos = false;
   for(int i=PositionsTotal()-1; i>=0; i--) {{
      if(PositionGetSymbol(i)==_Symbol && PositionGetInteger(POSITION_MAGIC)==InpMagic)
         has_pos = true;
   }}
   if(has_pos) return;
   
   //--- Entry logic: {entry}
   bool entry_long  = ({entry});
   bool entry_short = (!entry_long);  // Simplified inverse
   
   double sl = 0, tp = 0;
   if(entry_long || entry_short) {{
      atr_cache = iATR(_Symbol, PERIOD_CURRENT, 14);
      sl = (entry_long ? bid : ask) - (entry_long ? 1 : -1) * atr_cache * InpSlAtrMult;
      tp = (entry_long ? bid : ask) + (entry_long ? 1 : -1) * atr_cache * InpSlAtrMult * InpTpRr;
   }}
   
   if(entry_long) {{
      double lots = NormalizeDouble((AccountBalance() * InpRiskPercent/100) / (MathAbs(bid-sl)/point * SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE)), 2);
      trade.Buy(lots, _Symbol, ask, sl, tp, "{NAME}");
   }}
   else if(entry_short) {{
      double lots = NormalizeDouble((AccountBalance() * InpRiskPercent/100) / (MathAbs(sl-ask)/point * SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE)), 2);
      trade.Sell(lots, _Symbol, bid, sl, tp, "{NAME}");
   }}
}}
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {{ /* cleanup */ }}
//+------------------------------------------------------------------+
'''
    return code


def generate_python(spec):
    """Generate a Python backtestable strategy class."""
    code = f'''#!/usr/bin/env python3
"""
Strategy: {NAME}
Type: {TYPE}
Auto-generated by Trading OS Swarm
"""
import numpy as np
from dataclasses import dataclass
from typing import List, Optional

@dataclass
class Signal:
    side: str   # "BUY" or "SELL"
    confidence: float
    sl: Optional[float] = None
    tp: Optional[float] = None
    meta: dict = None

class {NAME}:
    """{spec.get("description", "Auto-generated strategy")}"""
    
    def __init__(self, risk_per_trade={spec.get("risk_per_trade", 1.0)}):
        self.risk = risk_per_trade
        self.indicators = {spec.get("indicators", [])}
        self.name = "{NAME}"
    
    def analyze(self, df) -> Optional[Signal]:
        """
        df: DataFrame with OHLCV + indicator columns.
        Returns Signal or None.
        """
        if len(df) < 30:
            return None
        
        last = df.iloc[-1]
        prev = df.iloc[-2]
        
        # Entry logic: {spec.get("entry_logic", "true")}
        entry_long = ({spec.get("entry_logic", "True")})
        entry_short = False  # TODO: define short logic
        
        if entry_long:
            atr = last.get("ATR14", last["close"] * 0.001)
            sl = last["close"] - atr * {spec.get("sl_atr_mult", 1.5)}
            tp = last["close"] + atr * {spec.get("sl_atr_mult", 1.5)} * {spec.get("tp_rr", 2.0)}
            return Signal(
                side="BUY",
                confidence=0.75,
                sl=round(sl, 5),
                tp=round(tp, 5),
                meta={{"strategy": "{NAME}", "timeframe": "{spec.get("timeframe", "H1")}"}}
            )
        return None
    
    def on_bar(self, df):
        return self.analyze(df)

if __name__ == "__main__":
    # Self-test with mock data
    import pandas as pd
    dates = pd.date_range("2024-01-01", periods=100, freq="H")
    df = pd.DataFrame({{
        "open": 1.1000 + np.random.randn(100).cumsum() * 0.001,
    }}, index=dates)
    df["high"] = df["open"] + abs(np.random.randn(100)) * 0.0005
    df["low"] = df["open"] - abs(np.random.randn(100)) * 0.0005
    df["close"] = (df["open"] + df["high"] + df["low"]) / 3 + np.random.randn(100) * 0.0002
    df["volume"] = np.random.randint(1000, 10000, 100)
    
    strat = {NAME}()
    signal = strat.analyze(df)
    print("Signal:", signal)
'''
    return code


def run():
    target = TASK.get("target", "python")
    code = generate_mql5(SPEC) if target == "mql5" else generate_python(SPEC)
    result = {
        "agent": "code_gen",
        "ts": time.time(),
        "strategy_id": NAME,
        "target": target,
        "code_length": len(code),
        "code": code,
    }
    with open(OUT, "w") as f:
        json.dump(result, f, indent=2)
    print(f"Code generation complete. Wrote {OUT} ({len(code)} chars)")

if __name__ == "__main__":
    run()
